version: '3.9'
services:
  db:
    image: mysql:8.0.37
    restart: never
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: 'user-123'
      MYSQL_PASSWORD: 'password-123'
      MYSQL_ROOT_PASSWORD: rootpass
