version: '3.9'
services:
  db:
    image: mysql:8.0.37
    container_name: mysql-ut-proj
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: 'user-123'
      MYSQL_PASSWORD: 'password-123'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    networks:
      - db-test

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin-ut-proj
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    networks:
      - db-test

networks:
  db-test:
    driver: bridge
